### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reiz** [haf/semver#7]
Would be nice to define a license in the gemspec ;-) Maybe MIT ;)

**Comment by haf** [comment]
Thx!

**Comment by walterg2** [comment]
Any chance this change can get pushed to Rubygems? Without it, other gems ensuring we're in line with our licensing requirements (like [`license_finder`](https://github.com/pivotal/LicenseFinder) can't pick up the proper license.

**Comment by reiz** [comment]
@walterg2 You can get the information from VersionEye: https://www.versioneye.com/ruby/semver2/3.4.2. Feel free to use our [API](https://www.versioneye.com/api/). By the way we have a feature which checks our dependencies against a license whitelist. It's also includes license normalisation. I guess our projects are very similar, we should meet for code & beer ;-)
