### ISSUE TITLE
Semver inside gemspec.

### ISSUE THREAD

**Issue by bjubinville** [haf/semver#9]
Hi,

A colleague posted this on the parent repo.  Thought I'd cross-post here:

https://github.com/flazz/semver/issues/11

Thanks for any insight.

**Comment by haf** [comment]
It's a different gem by now though...

You can do

```
gem.version = `semver`
```

perhaps?

**Comment by bjubinville** [comment]
Thanks @haf.  We're using your version of the gem.  My colleague just posted to the incorrect repo.

I'll give that a shot.

**Comment by bjubinville** [comment]
@haf it seems everything requires semver2 to be pre-installed and not listed as a dependency in the gemspec.  There doesn't appear to be a way to tell bundler to "install this first before doing anything else".

Any other ideas?

**Comment by haf** [comment]
`VERSION = begin ; SemVer.find.to_s ; rescue => e ; "0.0.0" ; end`

Perhaps?
